[phases.setup]
nixPkgs = ["php82Full", "nodejs", "npm"]

[phases.install]
cmds = [
  "curl -sS https://getcomposer.org/installer | php",
  "php composer.phar install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build",
  "php artisan config:cache",
  "php artisan migrate --force"
]

[start]
cmd = "php -S 0.0.0.0:8080 -t public"
